### ISSUE TITLE
prrqr missing in @hss/private

### ISSUE THREAD

**Issue by bonevbs** [numpi/hm-toolbox#2]
It seems prrqr(.) is missing in @hss, if I choose `hssoption('comression', 'qr')`, I get an error message. Copying prrqr.m to @hss/private seems to resolve it.

**Comment by robol** [comment]
Thanks for reporting the issue! I checked and the file is indeed missing. It will be fixed soon.

**Comment by bonevbs** [comment]
Hi Leonardo thanks!
