### ISSUE TITLE
Minor bug in hss_from_random_sampling

### ISSUE THREAD

**Issue by bonevbs** [numpi/hm-toolbox#5]
Hi, just another bug that I found: the estimation of the norm fails for rectangular matrices. The code should be

```
nrm = svds(@(x,t) normest_afun(Afun, Afunt, x, t), ...
        [m n], 1, 'largest', ...
        struct('tol', 1e-2)); nrm = nrm(1);
```

**Comment by robol** [comment]
Thanks Boris for spotting this, I applied the change you suggest!
