### ISSUE TITLE
Slow performance of toeplitz_solve

### ISSUE THREAD

**Issue by CP-Vub** [numpi/hm-toolbox#6]
Dear authors of the hm-toolbox, 

First off, major thanks for writing and publishing this toolbox. It is very insightful to see the code behind the paper's methods for someone who's not a mathematician but does use quite a bit of linear algebra in his work (engineer). 

One of the issues I often run into in my personal work is the time it takes to solve systems with a large Toeplitz matrix. As I've been comparing fast and superfast algorithms for this purpose, I was eager to also check your toeplitz_solve method. However, on my computer it seems to perform very slow. Comparing the run times for toeplitz_solve and the backslash operator in MATLAB, the latter is more than 2 orders of magnitude faster for the example matrix size of 4096 used in the examples folder.  The following code:

```
n = 4096;
c = randn(n, 1);
r = randn(1, n);
c(1) = r(1);
T = toeplitz(c, r);
b = randn(n, 1);

tic
x_ref =  T \ b;
time_ref= toc

tic
x_superfast=toeplitz_solve(c,r,b);
time_superfast = toc 

time_decrease=(1-time_superfast/time_ref)*100; % in percent

norm(T * x_superfast - b)
```

gives me the following output: 
> time_ref =   0.4469secs 
> time_superfast =  168.6636secs

Am I doing something obviously wrong that's causing this slow performance? 

Thanks again for publishing this toolbox.

**Comment by robol** [comment]
Dear Ray, 
thanks for reporting this, it seems related to some issue in the compression phase. 

We are currently looking into this, and try to get it solved. If you increase the current tolerance (e.g., ```hssoption('threshold', 1e-8); ```) the problem should not be triggered. I'll keep this issue updated.

**Comment by CP-Vub** [comment]
Thanks for following it up! Indeed, `hssoption('threshold', 1e-8);` seems to fix the issue, as it runs now considerably quicker than matlab's backslash operator

**Comment by massei** [comment]
Dear Ray,

we realized that the bug was caused by the error propagation in matrix vector multiplication with toeplitz matrices; this caused an overestimation of the hssrank when the hss threshold is of the order of n * eps; the issue should now be solved. Thank you for spotting this and feel free to contact us if you encounter any further problems.

Best wishes,
Stefano
