### ISSUE TITLE
NaN values in zero matrix

### ISSUE THREAD

**Issue by PlatinumMike** [numpi/hm-toolbox#7]
Dear authors,
I have been playing around with this toolbox for a bit, and it's very neat.
But I ran into this issue, where sometimes my test matrix is a zero matrix and NaN pops up.

To get a HODLR matrix you can do
``mat1 = hodlr('zeros',1024);``
which works just fine.

But if I first build a dense matrix, and then convert it it gives problems:
``mat1 = zeros(1024);``
``mat2 = hodlr(mat1);``
Now take for instance this element:
``mat2.U12(1,1)``
which returns NaN.

This is worrying as some blocks of my matrix can be fully 0.
To get around this I added a tiny value 1.0e-40, and then there is no issue cropping up.
But ideally I wouldn't have to do this.

I will leave some more details here for reproducibility:
Using Matlab 2020a.
Using hm-toolbox version 0b76a6804507e2c1f7ecb5d815a74fcc7ab95b9b
OS: OpenSuse leap 15.0
HSS doesn't suffer from this problem, so ``mat2 = hss(mat1)`` works fine.

**Comment by robol** [comment]
Thanks for reporting the issue, I think I have identified the problem, and should push the fix shortly. In case this does not solve your problem, feel free to reopen it. 

Thanks for helping us improve hm-toolbox!
